### ISSUE TITLE
.bablerc in npm package

### ISSUE THREAD

**Issue by cymen** [JFusco/es6-event-emitter#1]
I'm trying to use this with react-native and ran into it trying to run the `.bablerc` file from within node_modules. It blows up because of the plugin not being present. Apparently, the convention is becoming not to ship the `.bablerc` in the npm package by adding it to `.npmignore`.

https://github.com/facebook/react-native/issues/4062

Are you onboard with that?

**Comment by JFusco** [comment]
I'm on board with that, we can just add it to the webpack config.
