### ISSUE TITLE
Cannot find module 'babel-runtime/helpers/classCallCheck'

### ISSUE THREAD

**Issue by hirasso** [JFusco/es6-event-emitter#5]
Hi there, your class looks promising! I am having problems, while trying it out: The compiler says this:
```
Error: Cannot find module 'babel-runtime/helpers/classCallCheck' from 'node_modules/es6-event-emitter/dist'
```
Any ideas what I should do about that?

**Comment by hirasso** [comment]
Actually, installing `babel-runtime` fixed this issue – maybe you should add it to your project's dependencies.

**Comment by JFusco** [comment]
Hi @hirasso 
Thanks for checking it out and trying it!  I appreciate the feedback, I might be able to remove that dependency all together. I'll give it a try and also update my devDependencies as some of them are out of date.

Thanks!

**Comment by JFusco** [comment]
@hirasso 
Doing a quick search - this looks like a `devDependencies` issue - when I update them, this issue should go away - it appears to be an internal babel-loader problem.

**Comment by hirasso** [comment]
@JFusco 
this would be great! Also, I will introduce a new issue in a sec ;)
