### ISSUE TITLE
add "once" listener

### ISSUE THREAD

**Issue by hirasso** [JFusco/es6-event-emitter#6]
Hi there, would it be possible to also introduce a new "once" listener?

**Comment by JFusco** [comment]
@hirasso - Sure! I can probably get to it tomorrow. Feel free to submit a pull request and a unit test!

**Comment by JFusco** [comment]
I'll also be submitting a patch to update the `devDependencies` to get rid of the babel-runtime underlying issue.

**Comment by hirasso** [comment]
@JFusco I am not very experienced with tests... But maybe I will find the time sometime to dig through your source code and learn how to do it. You are not in Berlin by any chance, to show me hot it's done?  ;)

**Comment by JFusco** [comment]
@hirasso - I'm not in Berlin, if you have the time it'd be great, my day job is pretty demanding these days. The patterns are all set, so is you follow closely, you should be able to understand what's going on.

Again, I'm working on a patch right now to update the `devDependencies` and making some improvements to the documentation `README`

After I get done with that, I'll work on some enhancements.

**Comment by JFusco** [comment]
Hi @hirasso 
Finally got around to adding this - available in `v1.10.0`
Please see here for release notes - https://github.com/JFusco/es6-event-emitter/releases/tag/v1.10.0
