### ISSUE TITLE
why the restriction on node version?

### ISSUE THREAD

**Issue by Morriz** [JFusco/es6-event-emitter#7]
Do you have a specific reason to lock your package to `>=7.7.0 <=8.1.x`?

TIA

**Comment by JFusco** [comment]
@Morriz 
No reason - it shouldn't matter what node or npm version you have...it's just habit from other build scripts I have - I can remove it :)

**Comment by JFusco** [comment]
@Morriz 
This is now taken care of in `1.10.2` - https://github.com/JFusco/es6-event-emitter/releases/tag/v1.10.2
